# Generated by Django 2.2.2 on 2019-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_remove_entrie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='comments',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='entrie',
            name='name',
            field=models.CharField(default='Team leader name Here', max_length=100),
        ),
    ]
