# Generated by Django 2.2.2 on 2019-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20190907_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=300)),
                ('notice', models.TextField(max_length=1000)),
            ],
        ),
    ]
